# Generated by Django 2.2.2 on 2019-06-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_status_tbl',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, default='canada', max_length=255)),
            ],
            options={
                'db_table': 'location_tbl',
            },
        ),
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unit_status_tbl',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('C', 'Condo'), ('S', 'Suite')], default='C', max_length=255)),
                ('number_of_bathrooms', models.PositiveIntegerField()),
                ('has_den', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location')),
                ('unit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UnitStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ApplicationStatus')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Location')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_info_tbl',
            },
        ),
        migrations.CreateModel(
            name='UnitSavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unit_saved_search_tbl',
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
